config/routes.rb
Incense::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "devise/registrations" }

  devise_scope :user do
    match '/signup' => 'devise/registrations#new', via: 'get', :as => :signup
    match '/sign-up' => 'devise/registrations#new', via: 'get'
    match '/sign_up' => 'devise/registrations#new', via: 'get'

    match '/signin' => 'devise/sessions#new', via: 'get', :as => :signin
    match '/sign-in' => 'devise/sessions#new', via: 'get'
    match '/sign_in' => 'devise/sessions#new', via: 'get'

    match '/logout' => 'devise/sessions#destroy', via: 'delete', :as => :logout

    match '/account' => 'devise/registrations#edit', via: 'get', :as => :account
  end

  root 'landing_page#index'
  match '/about' => 'pages#about', via: 'get', :as => :about

  match '/add-item' => 'inventory#add', via: 'post', :as => :add_item
  match '/delete-item' => 'inventory#delete', via: 'post', :as => :delete_item
  match '/update-item' => 'inventory#update', via: 'post', :as => :update_item

end

app/models/classification.rb
class Classification < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  before_create :generate_unique_item_id

  validates :name, presence: true
  validates :expiration, presence: true

  belongs_to :user

  protected

  def generate_unique_item_id
    self.unique_item_id = loop do
      unique_id_string = Digest::SHA1.hexdigest([Time.now, rand].join)
      break unique_id_string unless Item.exists?(unique_item_id: unique_id_string)
    end
  end
end

app/models/test.rb
class Test
  def print_incense_log
    Rails.logger.debug "Whenever job works"  
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :send_welcome_email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :items

  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController

  def add
    @user = User.find(current_user) 
    @name = params[:item][:name]
    @classification = params[:item][:classification]
    @formatted_expiration = Date.parse(params[:item]["expiration(3i)"] + '-'  + params[:item]["expiration(2i)"] + '-'  + params[:item]["expiration(1i)"] )
    @item_status = 1

    if @name.nil?
      data['error_msg'] = "Please provide a name for the item you'd like to add."
      render :json => data
    else
      @item = Item.new
      @item.user_id = @user.id
      @item.name = @name
      @item.item_status_id = @item_status
      @item.expiration = @formatted_expiration
      @item.save!

      Rails.logger.debug @item.unique_item_id

      respond_to do |format|
        format.html { render :partial => "inventory_item", :layout => false, :locals => { :unique_id => @item.unique_item_id, :name => @name, :expiration => @formatted_expiration} }
      end
    end
  end

  def delete
  end

  def update
  end

end





app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController

  def index
    @date = Date.today.in_time_zone
    @item = Item.new
    @classifications = Classification.all
    if user_signed_in?
      @inventory_items = User.find(current_user).items
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def app_name 
    "Incense"
  end

  def current_year
    DateTime.now.strftime( "%Y" )
  end 
end

app/views/inventory/_inventory_item.html.haml
.row.current-item{ :id => "item-" + unique_id}
  %button.btn.btn-default.email-notification.pull-left
    %span{ :class => 'ss-icon header-icons' }
      E
  %button.btn.btn-success.in-app-notification.pull-left
    %span{ :class => 'ss-icon header-icons' }
      M
  .col-sm-6.col-md-6.col-lg-6
    .h4like.text-center
      #{name}
    %span
      .date
        %b
          #{expiration}

  %button.btn.btn-danger.delete.pull-right
    %span{ :class => 'ss-icon header-icons' }
      &#x2421;
  %button.btn.btn-warning.accept.pull-right
    %span{ :class => 'ss-icon header-icons' }
      &#x2713;

app/views/landing_page/_section_feature_thumbnails.html.haml
.hidden-xs
  .col-sm-3.col-md-3.col-lg-3.feature-card.border-left
    .ss-icon.text-center.font-size-40
      &#xF072;
    %h4
      Mark the date.
  .col-sm-1.col-md-1.col-lg-1.flow-arrows.color-green-darker.ss-icon
    &#x27A1;
  .col-sm-3.col-md-3.col-lg-3.feature-card
    .ss-icon.text-center.font-size-40
      &#x1F514;
    %h4
      Set how you want to be notified.
  .col-sm-1.col-md-1.col-lg-1.flow-arrows.color-green-darker.ss-icon
    &#x27A1;
  .col-sm-3.col-md-3.col-lg-3.feature-card.border-right
    .ss-icon.text-center.font-size-40
      &#x2139;
    %h4
      Incense will notify you when the expiration date is near.
.visible-xs
  .feature-card
    .ss-icon.text-center.font-size-40
      &#xF072;
    %h4
      Mark the date.
  .flow-arrows.color-green-darker.ss-icon
    &#x2B07;
  .feature-card
    .ss-icon.text-center.font-size-40
      &#x1F514;
    %h4
      Set how you want to be notified.
  .flow-arrows.color-green-darker.ss-icon
    &#x2B07;
  .feature-card
    .ss-icon.text-center.font-size-40
      &#x2139;
    %h4
      Incense will notify you when the expiration date is near.

app/views/landing_page/_section_marketing.html.haml
.jumbotron.text-center
  .container
    .col-sm-12
      %h1.text-center
        Wasting food sucks. Wasting money sucks more.
      %br
      .col-sm-6.col-sm-offset-3
        %h3
          Incense keeps track of perishable foods in your fridge (or cabinet, or kitchen) and alerts you when something is about to spoil.
        %h3
          Never waste food or money again.
    .clearfix
    .btn.btn-warning.c2a-large#block-signup-button
      Sign up for free

    .sign-up-form
      = form_for(:user, :url => registration_path(:user), :html => { :class => "form-horizontal form", :role => "form", :style => "opacity:0;filter:alpha(opacity=0);" }) do |f|

        .form-group
          = f.label :email, :class => "control-label col-sm-3"
          .col-sm-7
            = f.email_field :email, :class => "form-control", :placeholder => "Email", :autofocus => true

        .form-group
          = f.label :password, :class => "control-label col-sm-3"
          .col-sm-7
            = f.password_field :password, :class => "form-control", :placeholder => "Password"

        .form-group
          = f.label :confirm_password, :class => "control-label col-sm-3"
          .col-sm-7
            = f.password_field :confirm_password, :class => "form-control", :placeholder => "Confirm Password"

        .form-group
          .col-sm-offset-3.col-sm-7
            = f.submit "Sign up", :class => "btn btn-block btn-warning c2a-large"

    .instructions
      .container.text-center
        = render :partial => "landing_page/section_feature_thumbnails"


%section
  .container


%section
  .container

app/views/landing_page/index.html.haml
- provide :title, 'Home'
- content_for :body_class, "landing_page"

- if user_signed_in?
  .container
    .row
      .col-sm-12.col-md-12.col-lg-12
        %h1
          Dashboard
    %hr
    .row
      .col-sm-7.col-md-7.col-lg-7
        %h3
          Current Items
        #current-inventory
          - if @inventory_items.present?
            - @inventory_items.each do |i|
              .row.current-item
                %button.btn.btn-default.email-notification.pull-left
                  %span{ :class => 'ss-icon header-icons' }
                    E
                %button.btn.btn-success.in-app-notification.pull-left
                  %span{ :class => 'ss-icon header-icons' }
                    M
                .col-sm-6.col-md-6.col-lg-6
                  .h4like.text-center
                    = i.name
                  %span
                    .date
                      Expiration:
                      %strong
                        = i.expiration.strftime( "%-m/%-d/%Y" )

                %button.btn.btn-danger.delete.pull-right
                  %span{ :class => 'ss-icon header-icons' }
                    &#x2421;
                %button.btn.btn-warning.accept.pull-right
                  %span{ :class => 'ss-icon header-icons' }
                    &#x2713;
          - else
            %p.gray_light
              <i>Add an item to the right to get tracking</i>



      .col-sm-5.col-md-5.col-lg-5
        %h3
          Add an item to track
        .col-sm-12.col-md-12.col-lg-12.add-item
          = form_for(@item, :url => add_item_path, :html => { :class => "form-horizontal add-item-form", :role => "form" } ) do |f|
            .form-group
              = f.label :name, :class => "control-label sr-only"
              = f.text_field :name, :class => "form-control", :placeholder => "Item Name", :autofocus => true
            .form-group
              = f.label :expiration, :class => "control-label sr-only"
              .h4like
                Expiration Date
              %p.help-block
                <i>MM/DD/YYYY</i>
              = f.date_select :expiration, :order => [:month, :day, :year], :include_blank => true, :use_short_month => true, :start_year => Time.now.year, :end_year => Time.now.year + 9, :html => { :class => "form-control" }
            .form-group
              = f.submit "Add Item", :class => "btn btn-block btn-warning c2a-large add-item-button"



- else
  .container
    = render :partial => 'landing_page/section_marketing'

app/views/layouts/_footer.html.haml
%footer
  %ol.breadcrumb.text-center
    %li
      &copy; #{current_year}
    %li
      Designed by:
      = link_to "@patschreiber", "#"
    %li
      All rights reserved
    %li
      Privacy Policy

app/views/layouts/_header.html.haml
.width-100.accent_color
  .navigation
    .container
      .navbar{ "role" => "navigation"}
        .navbar-header
          %button{ :class => "navbar-toggle btn btn-warning", :data => { :toggle => 'collapse', :target => '#collapsed-header' } }
            %span{ :class => 'ss-icon header-icons' }
              &#x2026;

          // Possibly move brand link to if signed in, go to account page and if not, go to root path
          = link_to "Incense", root_path, :class => "navbar-brand"
        - if user_signed_in?
          .collapse.navbar-collapse#collapsed-header
            %ul{ :class => "nav navbar-nav navbar-right" }
              %li
                = link_to root_path, method: "get" do
                  %span{ :class => 'ss-icon header-icons' }
                    &#x2302;
                  Dashboard
              %li
                = link_to "#", method: "get" do
                  %span{ :class => 'ss-icon header-icons' }
                    &#x1F4CA;
                  Stats
              %li
                = link_to account_path, method: "get" do
                  %span{ :class => 'ss-icon header-icons' }
                    &#x1F464;
                  Account
              %li
                = link_to "Logout", logout_path, method: "delete", :class => "btn btn-warning"
        - else
          .collapse.navbar-collapse#collapsed-header
            %ul{ :class => "nav navbar-nav" }
              %li
                = link_to "About", about_path
            %ul{ :class => "nav navbar-nav navbar-right" }
              %li
                = link_to "Sign In", new_user_session_path
              %li
                = link_to "Sign Up", signup_path, :class => "btn btn-warning"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = (yield :title).present? ? "#{yield :title} | Incense" : "Incense"
    = favicon_link_tag "favicon.ico"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{'http-equiv' => 'Content-Language', :content => 'en'}
    %meta{:content => "width=device-width", :name => "viewport", "initial-scale" => 1.0, "maximum-scale" => 1.0, "user-scalable" => "no"}
    - if content_for?(:meta_description)
      %meta{:content => yield(:meta_description), :name => "description" }

  %body{ :class => "#{yield :body_class}" }

    = render 'layouts/header'

    .col-sm-4.col-sm-offset-4
      - if flash[:notice]
        .alert.alert-warning.text-center.alert-dismissable
          %button{ :class => "close", :data => { :dismiss => "alert" } }
            x
          = flash[:notice]

      - if flash[:error]
        .alert.alert-danger.text-center.alert-dismissable
          %button{ :class => "close", :data => { :dismiss => "alert" } }
            x
          = flash[:error]

      - if flash[:alert]
        .alert.alert-danger.text-center.alert-dismissable
          %button{ :class => "close", :data => { :dismiss => "alert" } }
            x
          = flash[:alert]
    = yield
    = render 'layouts/footer'


app/views/pages/about.html.haml
.container
  .col-md-5
    %h1
      Why #{app_name}